[package]
name = "discover"
version = "0.1.0"
edition = "2024"

[dependencies]
futures = "0.3.31"
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1.17"
zbus = "5.9.0"
zvariant = "5.6.0"
