// # D-Bus interface proxy for: `org.freedesktop.Avahi.ServiceResolver`
//
// This code was generated by `zbus-xmlgen` `5.1.0` from D-Bus introspection data.
// Source: `ServiceResolverIntrospect.xml`.
//
// You may prefer to adapt it, instead of using it verbatim.
//
// More information can be found in the [Writing a client proxy] section of the zbus
// documentation.
//
// This type implements the [D-Bus standard interfaces], (`org.freedesktop.DBus.*`) for which the
// following zbus API can be used:
//
// * [`zbus::fdo::IntrospectableProxy`]
//
// Consequently `zbus-xmlgen` did not generate code for the above interfaces.
//
// [Writing a client proxy]: https://dbus2.github.io/zbus/client.html
// [D-Bus standard interfaces]: https://dbus.freedesktop.org/doc/dbus-specification.html#standard-interfaces,

#[proxy(
    interface = "org.freedesktop.Avahi.ServiceResolver",
    assume_defaults = true
)]
pub trait ServiceResolver {
    /// Free method
    fn free(&self) -> zbus::Result<()>;

    /// Failure signal
    #[zbus(signal)]
    fn failure(&self, error: &str) -> zbus::Result<()>;

    /// Found signal
    #[zbus(signal)]
    fn found(
        &self,
        interface: i32,
        protocol: i32,
        name: &str,
        type_: &str,
        domain: &str,
        host: &str,
        aprotocol: i32,
        address: &str,
        port: u16,
        txt: Vec<Vec<u8>>,
        flags: u32,
    ) -> zbus::Result<()>;
}
